<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>*.entities</string>
	</array>
	<key>name</key>
	<string>entities</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>keyword.control.entitiesdsl</string>
			<key>match</key>
			<string>\b(datatype|entity)\b</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.entitiesdsl</string>
</dict>
</plist>
