/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.entities


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class EntitiesDslRuntimeModule extends AbstractEntitiesDslRuntimeModule {
}
