/*
 * generated by Xtext 2.11.0-SNAPSHOT
 */
package org.xtext.example.entities.ide


/**
 * Use this class to register ide components.
 */
class EntitiesDslIdeModule extends AbstractEntitiesDslIdeModule {
}
